name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.15.0

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0

      - name: Build project
        run: npm run build

      - name: Cypress
        uses: cypress-io/github-action@v6.5.0
        env:
          CYPRESS_LOCALHOST: ${{secrets.CYPRESS_LOCALHOST}}
          CYPRESS_EMAIL: ${{secrets.CYPRESS_EMAIL}}
          CYPRESS_PASSWORD: ${{secrets.CYPRESS_PASSWORD}}
        with:
          start: npm run dev
